# Generated by Django 4.0.3 on 2022-03-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество книг'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость книги'),
        ),
    ]
