# Generated by Django 4.0.3 on 2022-03-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_books_quantity_alter_books_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на обложку'),
        ),
    ]
