# Generated by Django 4.0.3 on 2022-03-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_sellbooks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellBooks',
        ),
        migrations.AddField(
            model_name='books',
            name='quantity_sale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество книг на продажу'),
        ),
        migrations.AddField(
            model_name='books',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Продажа'),
        ),
    ]
